### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by dhslr** [dhslr/recipes_backend#3]
This repo does not yet use any github actions to build and test the app. There is already elixir (mix) support in github actions!

**Comment by rexdivakar** [comment]
Add me in this too pls @dhslr

**Comment by dhslr** [comment]
Just a heads up: I broke the tests by removing a dependency in my last PR. I have added it back. Just make sure you use the newest code base :)

**Comment by rexdivakar** [comment]
Hey @dhslr my test builds are failing during execution of mix test command with the below error, can you please check and let me know if this is a dependency error ?

![image](https://user-images.githubusercontent.com/15235122/193715606-916b151f-37d4-4400-a127-d9673a414883.png)

**Comment by dhslr** [comment]
Hi @rexdivakar,

strange I do not get this error. Maybe some dependencies are out of date. Can you try to trun `mix deps.clean --all && mix deps.get`, maybe this will help. 
Just making sure: you used the latest version of main branch to test this, right?

**Comment by rexdivakar** [comment]
Yes i did, trying with few tweaks, will keep u posted asap

**Comment by rexdivakar** [comment]
![image](https://user-images.githubusercontent.com/15235122/194685691-15d7d079-fd3d-413d-b5f9-2a4e32d8cbcf.png)


Can you pls share the commands u tried on ur local during the compilation ?

**Comment by dhslr** [comment]
Hello,

I have updated `Dockerfile` and `docker-compose.yml` now. The project should successfully build with docker again.
Just create a `.env` file in the root directory (use `.env.example` as a starting point). You just need to provide a `SECRET_KEY_BASE`. For testing you can use some random string like `zIgab4HSSy`.
After that a simple `docker-compose up` and should get you running!

Best Regards
Daniel

**Comment by rexdivakar** [comment]
will try it and let you know soon
