### ISSUE TITLE
Update Dockerfile to use newest elixir/erlang version

### ISSUE THREAD

**Issue by dhslr** [dhslr/recipes_backend#4]
Versions could be bumped to elixir 1.14 and erlang 25.x

**Comment by rexdivakar** [comment]
Hey @dhslr please assign this to me, I will update the Dockerfile with modern safer practices

**Comment by dhslr** [comment]
Sure thing, thank you in advance! :)

**Comment by dhslr** [comment]
Just a heads up: I broke the tests by removing a dependency in my last PR. I have added it back. Just make sure you use the newest code base :)
